import { createFileRoute } from '@tanstack/react-router'
import { useState, type FormEvent } from 'react'
import { ArrowRight, BadgeCheck, Banknote, BarChart3, BellRing, BookOpen, Building2, Check, CheckCircle2, ChevronDown, Cloud, FileCheck2, HandCoins, Landmark, LockKeyhole, Menu, ReceiptIndianRupee, ShieldCheck, TrendingUp, Upload, Users, X } from 'lucide-react'

export const Route = createFileRoute('/')({ component: Home })
const hisab = [['Track customer payments',ReceiptIndianRupee],['Manage credit & debit entries',BookOpen],['Smart payment reminders',BellRing],['Clear business reports',BarChart3],['Secure cloud records',Cloud]] as const
const loans = [['Unsecured Business Loan','Up to ₹50 Lakhs'],['Secured Business Loan','Up to ₹5 Crores'],['Loan Against Property','Up to ₹10 Crores'],['Supply Chain Finance','Flexible limits'],['Dealer Finance','Built for growth'],['Vendor Finance','Better cash flow']]
const faqs = [['Does Nafabook provide loans directly?','No. Nafabook connects eligible businesses with RBI-regulated NBFCs and Scheduled Banks. The lending partner makes the final credit decision.'],['Who can apply for business finance?','Indian MSMEs, proprietors, partnerships and companies can apply. Eligibility depends on business vintage, turnover, banking history and lender policy.'],['Is my business data secure?','We use secure workflows and controlled access practices for your business records and application documents.'],['What documents are required?','Keep your PAN, Aadhaar, GST Certificate and the latest six months of bank statements ready. A lender may request additional documents.']]

function Logo({light=false}:{light?:boolean}){return <a className={`logo ${light?'light':''}`} href="#top" aria-label="Nafabook home"><svg viewBox="0 0 44 44"><path d="M7 8h14c5 0 8 3 8 7v21H14c-4 0-7-3-7-7V8Z"/><path d="M29 16h7v20h-7M14 17h8M14 23h8"/><path className="profit" d="m20 31 7-7 4 4 7-9M33 19h5v5"/></svg><b>Nafa<span>book</span></b></a>}

function Home(){
 const [menu,setMenu]=useState(false),[modal,setModal]=useState(false),[step,setStep]=useState(1),[done,setDone]=useState(false),[sending,setSending]=useState(false),[error,setError]=useState('')
 const open=()=>{setModal(true);setMenu(false);document.body.style.overflow='hidden'}, close=()=>{setModal(false);document.body.style.overflow=''}
 const next=(target:number)=>{const fields=document.querySelectorAll<HTMLInputElement|HTMLSelectElement>('.formstep.active input:not([type="hidden"]), .formstep.active select');for(const field of fields){if(!field.reportValidity())return}setStep(target)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSending(true);setError('');try{const r=await fetch('/__forms.html',{method:'POST',body:new FormData(e.currentTarget)});if(!r.ok)throw Error();setDone(true)}catch{setError('We could not submit your application. Please try again or email hello@nafabook.com.')}finally{setSending(false)}}
 return <div id="top">
  <header><nav className="shell nav"><Logo/><div className={`navlinks ${menu?'open':''}`}><a href="#solutions">Solutions</a><a href="#why">Why Nafabook</a><a href="#how">How it works</a><a href="#faqs">FAQs</a><button className="btn small" onClick={open}>Apply now <ArrowRight/></button></div><button className="menubtn" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></nav></header>
  <main>
   <section className="shell hero">
    <div className="hero-copy"><p className="eyebrow">Built for India’s growing businesses</p><h1>Hisab Sahi,<br/><em>Nafa Zyada.</em></h1><p className="lede">Smart business accounting and quick access to business finance for growing MSMEs.</p><div className="actions"><a className="btn" href="#solutions">Explore Nafabook <ArrowRight/></a><button className="linkbtn" onClick={open}>Apply for finance ↗</button></div><div className="trust"><ShieldCheck/> Secure records <i/> <Landmark/> Trusted lending partners</div></div>
    <div className="visual"><div className="growth"><TrendingUp/><b>+18.6%</b><small>monthly inflow</small></div><div className="ledger"><div className="ledger-head"><Logo/><small>SEPT 2026</small></div><p>Net receivable</p><h3>₹1,42,850 <span><TrendingUp/>12.4%</span></h3><svg className="chart" viewBox="0 0 420 115" preserveAspectRatio="none"><path d="M0 100 C50 95 60 55 105 76 S160 94 205 55 S265 70 310 34 S360 48 420 7"/></svg><div className="entry"><i>VP</i><span><b>Vardhan Plastics</b><small>Invoice #NF-2841</small></span><strong>+ ₹28,400</strong></div><div className="entry"><i>SM</i><span><b>Shree Motors</b><small>Payment due tomorrow</small></span><strong className="due">₹12,650 due</strong></div></div><div className="reminder"><BellRing/><span><b>Payment reminder sent</b><small>To Shree Motors • just now</small></span><CheckCircle2/></div></div>
   </section>
   <div className="strip"><div className="shell"><p><b>One business platform.</b> Two ways to grow.</p><span>● Digital records　 ● Faster decisions　 ● Partner-led finance</span></div></div>
   <section className="shell section" id="solutions"><div className="heading"><div><p className="eyebrow">Our solutions</p><h2>From daily hisab to<br/>your next big leap.</h2></div><p>Simple tools to know where your money stands—and trusted finance options when your business is ready to move.</p></div><div className="solutions">
    <article className="solution"><small>01</small><BookOpen className="feature-icon"/><label>RUN YOUR BUSINESS</label><h3>Digital Hisab Kitab</h3><p>Replace scattered diaries and spreadsheets with one clear, always-available business ledger.</p><ul>{hisab.map(([t,I])=><li key={t}><I/>{t}<Check/></li>)}</ul><a href="mailto:hello@nafabook.com?subject=Digital%20Hisab%20Kitab">Get started with Hisab <ArrowRight/></a></article>
    <article className="solution dark"><small>02</small><HandCoins className="feature-icon"/><label>GROW YOUR BUSINESS</label><h3>Apply for Loan</h3><p>Tell us what your business needs. We help match you with suitable options from trusted lenders.</p><div className="loan-list">{loans.map(([n,a])=><div key={n}><span><CheckCircle2/>{n}</span><b>{a}</b></div>)}</div><button onClick={open}>Check finance options <ArrowRight/></button></article>
   </div></section>
   <section className="why" id="why"><div className="shell whygrid"><div><p className="eyebrow">Why Nafabook</p><h2>Clarity in your books.<br/><em>Confidence in your growth.</em></h2><p>Built for the people behind India’s small businesses—where every payment, every day, matters.</p><blockquote>“ Business finance works better when the numbers tell a clear story.</blockquote></div><div className="whycards">{[[ShieldCheck,'Trust comes first','Your records and documents are handled with care through secure digital workflows.'],[TrendingUp,'Growth, made practical','Useful insights for today, and finance pathways for the opportunity ahead.'],[Users,'Human help, when needed','Clear guidance through your application—not confusing financial jargon.'],[BadgeCheck,'Responsible partnerships','Finance products only through regulated NBFCs and Scheduled Banks.']].map(([I,t,d]:any)=><div key={t}><I/><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
   <section className="shell section" id="how"><div className="centerhead"><p className="eyebrow">A straightforward journey</p><h2>From interest to application<br/>in four simple steps.</h2></div><div className="steps">{[['01',HandCoins,'Apply now','Choose the right finance solution.'],['02',ShieldCheck,'Verify mobile','Confirm your mobile number securely.'],['03',Banknote,'Share details','Tell us about your business needs.'],['04',FileCheck2,'Upload documents','Add PAN, Aadhaar, GST and bank statements.']].map(([n,I,t,d]:any)=><div key={n}><small>{n}</small><i><I/></i><h3>{t}</h3><p>{d}</p></div>)}</div><button className="btn centered" onClick={open}>Start your application <ArrowRight/></button></section>
   <section className="partners"><div className="shell partnergrid"><div><p className="eyebrow">Lending network</p><h2>10+ trusted lending partners</h2><p>Access finance through established banking and NBFC partners, subject to eligibility.</p></div><div>{['Scheduled Banks','RBI-Regulated NBFCs','Secured Lenders','Supply Chain Partners'].map(x=><span key={x}><Building2/>{x}</span>)}</div></div></section>
   <section className="shell section faq" id="faqs"><div><p className="eyebrow">Common questions</p><h2>Good questions.<br/>Clear answers.</h2><p>Need more help? <a href="mailto:hello@nafabook.com">hello@nafabook.com</a></p></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown/></summary><p>{a}</p></details>)}</div></section>
   <section className="shell cta"><div><p className="eyebrow">Ready when you are</p><h2>Keep better hisab.<br/>Build a stronger business.</h2></div><div><button className="btn green" onClick={open}>Apply for finance <ArrowRight/></button><a href="mailto:hello@nafabook.com">hello@nafabook.com</a></div></section>
  </main>
  <footer><div className="shell footgrid"><div><Logo light/><p>Digital Hisab Kitab and business finance access for growing Indian MSMEs.</p></div><div><b>Explore</b><a href="#solutions">Solutions</a><a href="#why">Why Nafabook</a><a href="#how">How it works</a><a href="#faqs">FAQs</a></div><div><b>Contact us</b><a href="mailto:hello@nafabook.com">hello@nafabook.com</a><p>Near Oxygen Park, Old Mundhwa Road,<br/>Ganesh Nagar, Pune, Maharashtra 411410</p></div></div><div className="shell disclaimer">Nafabook is not an NBFC and does not provide loans directly. Loan products are offered through RBI regulated NBFCs and Scheduled Banks. Loan approval is subject to lender policies and eligibility criteria.</div><div className="shell copyright">© 2026 Nafabook. All rights reserved. <span>Hisab Sahi, Nafa Zyada</span></div></footer>
  {modal&&<div className="overlay" role="dialog" aria-modal="true"><button className="underlay" onClick={close}/><aside className="modal"><button className="close" onClick={close}><X/></button>{!done?<><div className="modalhead"><p className="eyebrow">Finance application</p><h2>{step===1?'Let’s start with your mobile.':step===2?'Tell us about your business.':'Upload your documents.'}</h2><p>Step {step} of 3</p><i><span style={{width:`${step/3*100}%`}}/></i></div><form name="loan-application" method="POST" encType="multipart/form-data" data-netlify="true" netlify-honeypot="bot-field" onSubmit={submit}><input type="hidden" name="form-name" value="loan-application"/><input type="hidden" name="bot-field"/><input type="hidden" name="application-stage" value="completed"/>
   <div className={step===1?'formstep active':'formstep'}><label>Mobile number<input name="mobile" type="tel" inputMode="numeric" pattern="[0-9]{10}" placeholder="10-digit mobile number" required/></label><p className="note"><LockKeyhole/> Used only for your application and follow-up.</p><button type="button" className="btn full" onClick={()=>next(2)}>Verify & continue <ArrowRight/></button></div>
   <div className={step===2?'formstep active':'formstep'}><div className="formrow"><label>Full name<input name="full-name" placeholder="Your full name" required/></label><label>Business name<input name="business-name" placeholder="Registered / trade name" required/></label></div><div className="formrow"><label>Business type<select name="business-type" required defaultValue=""><option value="" disabled>Select type</option><option>Proprietorship</option><option>Partnership</option><option>Private Limited</option><option>LLP</option></select></label><label>Finance required<select name="finance-type" required defaultValue=""><option value="" disabled>Select option</option>{loans.map(([x])=><option key={x}>{x}</option>)}</select></label></div><label>Required amount (₹)<input name="required-amount" type="number" min="100000" placeholder="e.g. 1000000" required/></label><div className="formnav"><button type="button" onClick={()=>setStep(1)}>Back</button><button type="button" className="btn" onClick={()=>next(3)}>Continue <ArrowRight/></button></div></div>
   <div className={step===3?'formstep active':'formstep'}><p className="uploadnote">PDF, JPG or PNG • Combined upload must be under 8 MB</p><div className="uploads">{[['pan','PAN card'],['aadhaar','Aadhaar card'],['gst-certificate','GST certificate'],['bank-statement','Last 6 months bank statement']].map(([n,l])=><label className="upload" key={n}><Upload/><span><b>{l}</b><small>Choose a file</small></span><input type="file" name={n} accept=".pdf,.jpg,.jpeg,.png" required/></label>)}</div><label className="consent"><input type="checkbox" name="consent" value="yes" required/>I consent to Nafabook sharing these details with suitable lending partners to process my application.</label>{error&&<p className="error">{error}</p>}<div className="formnav"><button type="button" onClick={()=>setStep(2)}>Back</button><button className="btn" disabled={sending}>{sending?'Submitting…':'Submit application'} <ArrowRight/></button></div><p className="privacy"><ShieldCheck/>Documents may contain sensitive data. Configure Netlify’s VGS integration for enhanced production protection.</p></div>
  </form></>:<div className="success"><i><Check/></i><h2>Thank you for your interest.</h2><p>Our representative will contact you shortly.</p><button className="btn" onClick={close}>Back to Nafabook</button></div>}</aside></div>}
 </div>
}
